.PHONY: test
test:
	go test -timeout 30s -run ^TestSelection$   github.com/pingcap/tidb/hbase	--tags=intest 
test2:
	go test -timeout 30s -tags intest -run ^TestSelection$   github.com/pingcap/tidb/hbase	
